"""Regenerate ward affordability data from the archived community CSVs.

Reads the three Zillow ward-affordability sheets archived under
``docs/data/zillow-affordability/`` (hand-collected by Collin Pearsall with
hand-drawn ward boundaries; see the README there and methodology doc §7) and
writes the committed data module ``app/data/ward_affordability_data.py``:

- ``WARD_AFFORDABILITY`` — ward → affordability values (display keys
  ``affordable_share_pct`` and ``affordability_rank_change`` plus audit context)
- ``AFFORDABILITY_META`` — vintage, attribution, citywide summary

Parsing and cross-checks live in ``app.imports.sources.affordability``; any
column drift or inconsistency between the sheets aborts without writing.

Usage:
    python -m scripts.fetch_affordability_data
"""

from __future__ import annotations

import logging
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from app.imports.sources.affordability import build_ward_affordability

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("fetch-affordability")

ARCHIVE_DIR = (
    Path(__file__).resolve().parent.parent.parent
    / "docs"
    / "data"
    / "zillow-affordability"
)
CSV_2025 = ARCHIVE_DIR / "zillow-affordability-2025.csv"
CSV_2026 = ARCHIVE_DIR / "zillow-affordability-2026.csv"
CSV_COMPARISON = ARCHIVE_DIR / "zillow-affordability-2025-vs-2026.csv"

DATA_DIR = Path(__file__).resolve().parent.parent / "app" / "data"
OUTPUT_PATH = DATA_DIR / "ward_affordability_data.py"

# End of the 2026 collection window — the vintage shown on the scorecard.
AS_OF = "2026-07-28"
SOURCE = (
    "Community-collected Zillow listings survey "
    "(hand-drawn ward boundaries, by Collin Pearsall)"
)
COLLECTION_WINDOWS = {"2025": "2025-07-25/2025-07-27", "2026": "2026-07-25/2026-07-28"}


def _ruff_format(path: Path) -> None:
    """Best-effort `ruff format` on a generated file so re-runs stay compliant."""
    try:
        subprocess.run(
            [sys.executable, "-m", "ruff", "format", str(path)],
            check=True,
            capture_output=True,
        )
    except (subprocess.CalledProcessError, FileNotFoundError) as exc:
        logger.warning("Could not ruff-format %s (%s); format it manually.", path, exc)


def write_affordability_module(
    wards: dict[int, dict[str, float | int | str | None]],
    meta: dict[str, Any],
    path: Path | None = None,
) -> None:
    out_path = path if path is not None else OUTPUT_PATH
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S")
    lines = [
        "# Auto-generated by scripts/fetch_affordability_data.py",
        "# Source: community Zillow survey archived in docs/data/zillow-affordability/",
        f"# Generated: {timestamp}",
        f"# as-of: {meta.get('as_of')}",
        "WARD_AFFORDABILITY: dict[int, dict[str, float | int | str | None]] = {",
    ]
    # Emit Python literals (repr), not str/JSON — None values and strings must
    # round-trip on import.
    for ward in sorted(wards):
        body = ", ".join(f'"{k}": {v!r}' for k, v in wards[ward].items())
        lines.append(f"    {ward}: {{{body}}},")
    lines.append("}")
    lines.append("")
    lines.append(f"AFFORDABILITY_META = {dict(sorted(meta.items()))!r}")
    lines.append("")
    out_path.write_text("\n".join(lines), encoding="utf-8")
    _ruff_format(out_path)
    logger.info("Wrote %s", out_path)


def main() -> None:
    wards, citywide = build_ward_affordability(
        CSV_2025.read_text(encoding="utf-8-sig"),
        CSV_2026.read_text(encoding="utf-8-sig"),
        CSV_COMPARISON.read_text(encoding="utf-8-sig"),
    )
    meta: dict[str, Any] = {
        "as_of": AS_OF,
        "source": SOURCE,
        "collection_windows": COLLECTION_WINDOWS,
        "boundary_method": (
            "hand-drawn Zillow custom regions approximating the 2023 ward map"
        ),
        **citywide,
    }
    write_affordability_module(wards, meta)
    logger.info("Done. %d wards.", len(wards))


if __name__ == "__main__":
    main()
