"""Zoning-delay audit service — per-matter drill-down behind the ward metrics.

Serves the committed per-matter records (``app.data.ward_zoning_matters``,
generated by ``scripts/fetch_zoning_delay_data.py``) with per-matter
span/stalled/pending/withdrawn flags derived at request time against the
dataset's frozen as-of date, using the same date-parsing and withdrawal rules
as ``compute_ward_delay_stats``. The per-ward aggregate numbers come straight
from the committed ``WARD_ZONING_DELAY`` (single source of truth with the
scorecard); the derivation here exists so the audit table provably reconciles
with them.
"""

import logging
from datetime import date
from typing import Any
from uuid import UUID

from app.db.base import DatabaseProvider
from app.imports.sources.ward_utils import parse_ward_number
from app.imports.sources.zoning_delay import (
    STALLED_THRESHOLD_DAYS,
    is_withdrawn,
    parse_elms_date,
)
from app.models.pydantic.models import (
    WardAffordability,
    ZoningAuditMatter,
    ZoningAuditResponse,
    ZoningAuditWard,
)

logger = logging.getLogger(__name__)

# All three modules are generated; import defensively so the service (and its
# tests) degrade to an empty dataset rather than crashing the app at import.
try:  # pragma: no cover - trivial import guard
    from app.data.ward_zoning_matters import (
        UNASSIGNED_ZONING_MATTERS,
        WARD_ZONING_MATTERS,
    )
except ImportError:  # pragma: no cover
    WARD_ZONING_MATTERS = {}
    UNASSIGNED_ZONING_MATTERS = []

try:  # pragma: no cover - trivial import guard
    from app.data.ward_zoning_delay_data import WARD_ZONING_DELAY, ZONING_DELAY_META
except ImportError:  # pragma: no cover
    WARD_ZONING_DELAY = {}
    ZONING_DELAY_META = {}

try:  # pragma: no cover - trivial import guard
    from app.data.ward_affordability_data import AFFORDABILITY_META, WARD_AFFORDABILITY
except ImportError:  # pragma: no cover
    WARD_AFFORDABILITY = {}
    AFFORDABILITY_META = {}


def derive_matter_flags(matter: dict[str, Any], as_of: date) -> ZoningAuditMatter:
    """Build the response row for one matter, deriving audit flags.

    Mirrors ``compute_ward_delay_stats`` exactly: sentinel dates parse to None,
    a withdrawal is neither resolved-for-the-median nor pending, ``span_days``
    is present for any valid non-negative introduction → final-action pair
    (the ``withdrawn`` flag tells the auditor when it was excluded from the
    median anyway), and ``stalled`` is a pending matter older than the
    threshold at the frozen as-of date.
    """
    introduced = parse_elms_date(matter.get("introduction_date"))
    finalized = parse_elms_date(matter.get("final_action_date"))
    withdrawn = is_withdrawn(matter.get("sub_status"))

    span_days: int | None = None
    stalled = False
    pending = False
    if finalized is not None:
        if introduced is not None and (finalized - introduced).days >= 0:
            span_days = (finalized - introduced).days
    elif not withdrawn:
        pending = True
        stalled = (
            introduced is not None
            and (as_of - introduced).days > STALLED_THRESHOLD_DAYS
        )

    return ZoningAuditMatter(
        record_number=str(matter.get("record_number") or ""),
        matter_guid=str(matter.get("matter_guid") or ""),
        title=matter.get("title"),
        address=matter.get("address"),
        introduction_date=matter.get("introduction_date"),
        final_action_date=matter.get("final_action_date"),
        status=matter.get("status"),
        sub_status=matter.get("sub_status"),
        lat=matter.get("lat"),
        lon=matter.get("lon"),
        near_boundary=bool(matter.get("near_boundary")),
        span_days=span_days,
        stalled=stalled,
        pending=pending,
        withdrawn=withdrawn,
    )


def _ward_affordability(ward: int) -> WardAffordability | None:
    """The ward's survey context, or None when the ward has no survey row.

    Keys are filtered to the model's fields so future additions to the
    generated module can't break the endpoint.
    """
    data = WARD_AFFORDABILITY.get(ward)
    if data is None:
        return None
    return WardAffordability.model_validate(
        {k: v for k, v in data.items() if k in WardAffordability.model_fields}
    )


class ZoningAuditService:
    """Assembles the zoning-audit drill-down for a Chicago council group."""

    def __init__(
        self,
        projects_provider: DatabaseProvider,
        entities_provider: DatabaseProvider,
        districts_provider: DatabaseProvider,
    ):
        self.projects_provider = projects_provider
        self.entities_provider = entities_provider
        self.districts_provider = districts_provider

    async def get_zoning_audit(
        self, group_id: UUID, group_name: str
    ) -> ZoningAuditResponse | None:
        """Build the audit response, or None when the group has no ward data.

        Returns None (→ 404 at the route) when the group has no active
        projects or none of its jurisdiction's entities resolve to a ward —
        i.e. it is not a Chicago City Council group.
        """
        projects = await self.projects_provider.filter_multiple(
            filters={"group_id": group_id, "status": "active"},
            in_filters=None,
        )
        if not projects:
            return None
        jurisdiction_id = projects[0].jurisdiction_id

        alder_by_ward = await self._alder_names_by_ward(jurisdiction_id)
        if not alder_by_ward:
            return None

        as_of = self._as_of_date()
        wards: list[ZoningAuditWard] = []
        for ward in range(1, 51):
            stats = WARD_ZONING_DELAY.get(ward, {})
            matters = [
                derive_matter_flags(m, as_of) for m in WARD_ZONING_MATTERS.get(ward, [])
            ]
            wards.append(
                ZoningAuditWard(
                    ward=ward,
                    alder_name=alder_by_ward.get(ward),
                    zoning_median_days=stats.get("zoning_median_days"),
                    zoning_matter_count=int(stats.get("zoning_matter_count") or 0),
                    zoning_stalled_count=int(stats.get("zoning_stalled_count") or 0),
                    n_resolved=int(stats.get("n_resolved") or 0),
                    n_pending=int(stats.get("n_pending") or 0),
                    matters=matters,
                    affordability=_ward_affordability(ward),
                )
            )

        return ZoningAuditResponse(
            group_name=group_name,
            jurisdiction_id=jurisdiction_id,
            meta=dict(ZONING_DELAY_META),
            affordability_meta=dict(AFFORDABILITY_META),
            wards=wards,
            unassigned_matters=[
                derive_matter_flags(m, as_of) for m in UNASSIGNED_ZONING_MATTERS
            ],
        )

    @staticmethod
    def _as_of_date() -> date:
        """The frozen as-of date the stalled flags are derived against."""
        raw = str(ZONING_DELAY_META.get("computed_at") or "")
        try:
            return date.fromisoformat(raw)
        except ValueError:
            # No committed data (or a malformed date): fall back to the term
            # start so derivation stays deterministic rather than clock-driven.
            return date(2023, 5, 15)

    async def _alder_names_by_ward(self, jurisdiction_id: UUID) -> dict[int, str]:
        entities = await self.entities_provider.filter(jurisdiction_id=jurisdiction_id)
        if not entities:
            return {}
        district_ids = [e.district_id for e in entities if e.district_id]
        if district_ids:
            districts = await self.districts_provider.filter_in("id", district_ids)
            district_map = {d.id: d.name for d in districts}
            for entity in entities:
                if entity.district_id and entity.district_id in district_map:
                    entity.district_name = district_map[entity.district_id]
        names: dict[int, str] = {}
        for entity in entities:
            ward = parse_ward_number(entity)
            if ward is not None:
                names.setdefault(ward, entity.name)
        return names
