"""Per-ward metric aggregation for the Chicago alderperson scorecard.

Merges three committed data sources into a single ward → metric-values mapping
consumed by ``scripts/import_scorecard_projects.py``:

- ``app.data.ward_zoning_delay_data.WARD_ZONING_DELAY`` — generated by
  ``scripts/fetch_zoning_delay_data.py`` (median zoning delay + stalled counts).
- ``app.data.alder_units_registry.ALDER_UNITS_REGISTRY`` — curated bonus/lost
  units with optional first-mention → passage durations.
- ``app.data.ward_affordability_data.WARD_AFFORDABILITY`` — generated by
  ``scripts/fetch_affordability_data.py`` from the community Zillow survey
  (affordable-listings share + year-over-year rank change).
"""

from __future__ import annotations

import statistics
from datetime import date
from typing import Any

from app.data.alder_units_registry import ALDER_UNITS_REGISTRY

# The zoning-delay and affordability modules are generated by fetch scripts.
# Import defensively so aggregation (and its tests) still work before the first
# fetch has run.
try:  # pragma: no cover - trivial import guard
    from app.data.ward_zoning_delay_data import WARD_ZONING_DELAY
except ImportError:  # pragma: no cover
    WARD_ZONING_DELAY = {}

try:  # pragma: no cover - trivial import guard
    from app.data.ward_affordability_data import WARD_AFFORDABILITY
except ImportError:  # pragma: no cover
    WARD_AFFORDABILITY = {}

# Metric keys sourced from the units registry (vs. the zoning-delay data).
_REGISTRY_METRIC_KEYS = ("bonus_units", "lost_units", "mention_to_passage_days")
# Metric keys sourced from the zoning-delay data. The matter count is surfaced
# as denominator context: a raw stalled count correlates with rezoning volume
# (corr ≈ 0.79 in the 2023–2027 data), so it must never render without it.
_ZONING_METRIC_KEYS = (
    "zoning_median_days",
    "zoning_matter_count",
    "zoning_stalled_count",
)
# Metric keys sourced from the community affordability survey. The survey data
# carries additional context keys (listing counts, ranks, medians) that stay
# module-only; only the two display keys reach the scorecard.
_AFFORDABILITY_METRIC_KEYS = ("affordable_share_pct", "affordability_rank_change")

_LOST_KINDS = {"downzone", "shrunk_development"}


def _parse_iso(value: Any) -> date | None:
    if not value:
        return None
    try:
        return date.fromisoformat(str(value)[:10])
    except ValueError:
        return None


def aggregate_units_registry(
    registry: list[dict[str, Any]],
) -> dict[int, dict[str, float | int]]:
    """Aggregate the curated units registry into per-ward metric values.

    Returns ward → {bonus_units, lost_units, mention_to_passage_days}.
    ``mention_to_passage_days`` is the median span over items that carry both a
    ``first_public_date`` and a ``date``; it is omitted when no such item exists.
    """
    result: dict[int, dict[str, float | int]] = {}
    for entry in registry:
        ward = entry.get("ward")
        if not isinstance(ward, int):
            continue
        bonus = 0
        lost = 0
        spans: list[int] = []
        for item in entry.get("items", []):
            kind = item.get("kind")
            delta = item.get("units_delta", 0)
            if not isinstance(delta, (int, float)):
                continue
            if kind == "upzone":
                bonus += int(delta)
            elif kind in _LOST_KINDS:
                lost += int(delta)

            first_public = _parse_iso(item.get("first_public_date"))
            passed = _parse_iso(item.get("date"))
            if first_public is not None and passed is not None:
                span = (passed - first_public).days
                if span >= 0:
                    spans.append(span)

        ward_metrics: dict[str, float | int] = {
            "bonus_units": bonus,
            "lost_units": lost,
        }
        if spans:
            ward_metrics["mention_to_passage_days"] = round(
                float(statistics.median(spans)), 1
            )
        result[ward] = ward_metrics
    return result


def build_ward_metric_values(
    zoning_delay: dict[int, dict[str, Any]] | None = None,
    registry: list[dict[str, Any]] | None = None,
    affordability: dict[int, dict[str, Any]] | None = None,
) -> dict[int, dict[str, float | int]]:
    """Merge the three data sources into ward → metric values.

    Only display-relevant keys are surfaced (``zoning_median_days``,
    ``zoning_stalled_count`` from the delay data; the registry aggregates; the
    affordability display keys). Keys whose value is None (e.g. a ward with no
    resolved matter) are omitted so the scorecard renders them as blank rather
    than a spurious zero.
    """
    delay = zoning_delay if zoning_delay is not None else WARD_ZONING_DELAY
    reg = registry if registry is not None else ALDER_UNITS_REGISTRY
    afford = affordability if affordability is not None else WARD_AFFORDABILITY

    registry_values = aggregate_units_registry(reg)
    merged: dict[int, dict[str, float | int]] = {}

    wards = set(delay) | set(registry_values) | set(afford)
    for ward in wards:
        values: dict[str, float | int] = {}
        ward_delay = delay.get(ward, {})
        for key in _ZONING_METRIC_KEYS:
            value = ward_delay.get(key)
            if isinstance(value, (int, float)):
                values[key] = value
        for key in _REGISTRY_METRIC_KEYS:
            value = registry_values.get(ward, {}).get(key)
            if isinstance(value, (int, float)):
                values[key] = value
        ward_afford = afford.get(ward, {})
        for key in _AFFORDABILITY_METRIC_KEYS:
            value = ward_afford.get(key)
            if isinstance(value, (int, float)):
                values[key] = value
        if values:
            merged[ward] = values
    return merged
