"""Per-ward metric aggregation for the Chicago alderperson scorecard.

Merges two committed data sources into a single ward → metric-values mapping
consumed by ``scripts/import_scorecard_projects.py``:

- ``app.data.ward_zoning_delay_data.WARD_ZONING_DELAY`` — generated by
  ``scripts/fetch_zoning_delay_data.py`` (median zoning delay + stalled counts).
- ``app.data.alder_units_registry.ALDER_UNITS_REGISTRY`` — curated bonus/lost
  units with optional first-mention → passage durations.
"""

from __future__ import annotations

import statistics
from datetime import date
from typing import Any

from app.data.alder_units_registry import ALDER_UNITS_REGISTRY

# The zoning-delay module is generated by the fetch script. Import defensively so
# aggregation (and its tests) still work before the first fetch has run.
try:  # pragma: no cover - trivial import guard
    from app.data.ward_zoning_delay_data import WARD_ZONING_DELAY
except ImportError:  # pragma: no cover
    WARD_ZONING_DELAY = {}

# Metric keys sourced from the units registry (vs. the zoning-delay data).
_REGISTRY_METRIC_KEYS = ("bonus_units", "lost_units", "mention_to_passage_days")
# Metric keys sourced from the zoning-delay data.
_ZONING_METRIC_KEYS = ("zoning_median_days", "zoning_stalled_count")

_LOST_KINDS = {"downzone", "shrunk_development"}


def _parse_iso(value: Any) -> date | None:
    if not value:
        return None
    try:
        return date.fromisoformat(str(value)[:10])
    except ValueError:
        return None


def aggregate_units_registry(
    registry: list[dict[str, Any]],
) -> dict[int, dict[str, float | int]]:
    """Aggregate the curated units registry into per-ward metric values.

    Returns ward → {bonus_units, lost_units, mention_to_passage_days}.
    ``mention_to_passage_days`` is the median span over items that carry both a
    ``first_public_date`` and a ``date``; it is omitted when no such item exists.
    """
    result: dict[int, dict[str, float | int]] = {}
    for entry in registry:
        ward = entry.get("ward")
        if not isinstance(ward, int):
            continue
        bonus = 0
        lost = 0
        spans: list[int] = []
        for item in entry.get("items", []):
            kind = item.get("kind")
            delta = item.get("units_delta", 0)
            if not isinstance(delta, (int, float)):
                continue
            if kind == "upzone":
                bonus += int(delta)
            elif kind in _LOST_KINDS:
                lost += int(delta)

            first_public = _parse_iso(item.get("first_public_date"))
            passed = _parse_iso(item.get("date"))
            if first_public is not None and passed is not None:
                span = (passed - first_public).days
                if span >= 0:
                    spans.append(span)

        ward_metrics: dict[str, float | int] = {
            "bonus_units": bonus,
            "lost_units": lost,
        }
        if spans:
            ward_metrics["mention_to_passage_days"] = round(
                float(statistics.median(spans)), 1
            )
        result[ward] = ward_metrics
    return result


def build_ward_metric_values(
    zoning_delay: dict[int, dict[str, Any]] | None = None,
    registry: list[dict[str, Any]] | None = None,
) -> dict[int, dict[str, float | int]]:
    """Merge zoning-delay data and the units registry into ward → metric values.

    Only display-relevant keys are surfaced (``zoning_median_days``,
    ``zoning_stalled_count`` from the delay data; the registry aggregates).
    Keys whose value is None (e.g. a ward with no resolved matter) are omitted
    so the scorecard renders them as blank rather than a spurious zero.
    """
    delay = zoning_delay if zoning_delay is not None else WARD_ZONING_DELAY
    reg = registry if registry is not None else ALDER_UNITS_REGISTRY

    registry_values = aggregate_units_registry(reg)
    merged: dict[int, dict[str, float | int]] = {}

    wards = set(delay) | set(registry_values)
    for ward in wards:
        values: dict[str, float | int] = {}
        ward_delay = delay.get(ward, {})
        for key in _ZONING_METRIC_KEYS:
            value = ward_delay.get(key)
            if isinstance(value, (int, float)):
                values[key] = value
        for key in _REGISTRY_METRIC_KEYS:
            value = registry_values.get(ward, {}).get(key)
            if isinstance(value, (int, float)):
                values[key] = value
        if values:
            merged[ward] = values
    return merged
